### Introduction

*Financial markets and systemic indicator*: Financial markets can undergo catastrophic meltdowns and may endure a delayed recovery as witnessed in the major crashes of 1929 and 2008. The development of early warning signals (EWS) of systemic risks in financial markets are largely based on statistical models. For example, empirical observation of volatility prior to 1987 crash has led to devising statistical estimators of volatility as EWS of impending financial crises. More recently, system risk in financial systems has been shown to be preceded by increasing cross correlations or information dissipation in various financial sectors. However, integrating theoretical approaches based on nonlinear dynamical systems with empirical and statistical methods to devise EWS of impending financial crises remain one of the open challenges. 

*Tipping points, criticla transitions and early warning signals*: Recent research has shown that nonlinear complex dynamical systems, such as climatic and ecological systems, may exhibit tipping points at which the system will abruptly shift from one state to another. Such transitions, also referred to as critical transitions, are qualitatively similar to financial meltdowns in exhibiting discontinuous state changes and delayed recovery to the original state. Theory shows that the system considerably slows down in its response to perturbations as it approaches a bifurcation point. This phenomenon, known as `critical slowing down', is expected to cause an increasing trend of autocorrelation which can be readily measured using time series data of the dynamical system. Furthermore, the system exhibits an increased variability and reddening of power-spectrum in its time series dynamics. Therefore, it has been argued that these generic statistical indicators could be used as robust early warning signals of impending critical transitions. 

*Empirical success*: The above theoretical predictions have been empirically tested using data from past climatic shifts, and laboratory and field experiments in ecological systems ranging from microbial populations to lake ecosystems. In the context of these theoretical and empirical advances, it has been suggested that  financial meltdowns are akin to abrupt critical transitions that occur near the tipping point of a system even for small perturbations. 

Motivated by these studies, in the manuscript [Guttal, et al, 2016, PLOS ONE](http://dx.plos.org/10.1371/journal.pone.0144198) we set out to ask whether financial crashes are indeed critical transitions and whether there are any EWS of impending economic crises. 